# Generated by Django 2.2 on 2020-04-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200424_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_weight',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
