# Generated by Django 2.2 on 2020-04-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('supplier_acronym', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tax_number', models.CharField(max_length=45)),
                ('phone', models.CharField(default=False, max_length=45)),
                ('mobile_phone', models.CharField(default=False, max_length=45)),
                ('other_phone_alternative', models.CharField(default=False, max_length=45)),
                ('fax', models.CharField(default=False, max_length=45)),
                ('site', models.CharField(default=False, max_length=200)),
                ('mailing_list', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='Y', max_length=1)),
                ('address', models.CharField(default=False, max_length=200)),
                ('postal_code', models.CharField(default=False, max_length=45)),
                ('city', models.CharField(default=False, max_length=45)),
                ('contact', models.CharField(max_length=256)),
                ('product_counter', models.IntegerField(blank=1)),
                ('service_counter', models.IntegerField(blank=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
