# Generated by Django 3.0.3 on 2020-02-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_finger_right', models.DecimalField(decimal_places=2, default=False, max_digits=15)),
                ('middle_finger_left', models.DecimalField(decimal_places=2, default=False, max_digits=15)),
                ('index_finger_right', models.DecimalField(decimal_places=2, default=False, max_digits=15)),
                ('index_finger_left', models.DecimalField(decimal_places=2, default=False, max_digits=15)),
                ('thumb_right', models.DecimalField(decimal_places=2, default=False, max_digits=15)),
                ('thumb_left', models.DecimalField(decimal_places=2, default=False, max_digits=15)),
                ('ring_finger_right', models.DecimalField(decimal_places=2, default=False, max_digits=15)),
                ('ring_finger_left', models.DecimalField(decimal_places=2, default=False, max_digits=15)),
                ('pinky_finger_right', models.DecimalField(decimal_places=2, default=False, max_digits=15)),
                ('pinky_finger_left', models.DecimalField(decimal_places=2, default=False, max_digits=15)),
                ('wrist_right', models.DecimalField(decimal_places=2, default=False, max_digits=15)),
                ('wrist_left', models.DecimalField(decimal_places=2, default=False, max_digits=15)),
                ('neck', models.DecimalField(decimal_places=2, default=False, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'prefixes',
            },
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('mobile_phone', models.CharField(max_length=45)),
                ('wedding_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('measurement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Measurement')),
                ('prefix', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Prefix')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=100)),
                ('address', models.CharField(default=False, max_length=100)),
                ('phone', models.CharField(default=False, max_length=45)),
                ('postal_code', models.CharField(default=False, max_length=45)),
                ('city', models.CharField(default=False, max_length=45)),
                ('country', models.ForeignKey(default='PT', on_delete=django.db.models.deletion.CASCADE, to='clients.Country')),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('mobile_phone', models.CharField(max_length=45)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('E', 'Empresa')], max_length=1)),
                ('marital_status', models.CharField(choices=[('1', 'Solteiro'), ('2', 'Divorciado'), ('3', 'Casado'), ('4', 'Viuvo')], max_length=1)),
                ('tax_number', models.CharField(max_length=45)),
                ('civil_id', models.CharField(blank=True, max_length=45)),
                ('passport_id', models.CharField(blank=True, max_length=45)),
                ('phone', models.CharField(blank=True, max_length=45)),
                ('other_phone_alternative', models.CharField(blank=True, max_length=45)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site', models.CharField(blank=True, max_length=200)),
                ('fax', models.CharField(blank=True, max_length=45)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('mailing_list', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('postal_code', models.CharField(blank=True, max_length=45)),
                ('city', models.CharField(blank=True, max_length=45)),
                ('nib', models.CharField(blank=True, max_length=128)),
                ('notes', models.CharField(blank=True, max_length=1024)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('date_last_visit', models.DateField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Company')),
                ('country', models.ForeignKey(default='PT', on_delete=django.db.models.deletion.CASCADE, to='clients.Country')),
                ('measurement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Measurement')),
                ('prefix', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Prefix')),
                ('spouse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Spouse')),
            ],
        ),
    ]
