# Generated by Django 2.2 on 2020-04-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200423_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spouse',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='wedding_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
