# Generated by Django 2.2 on 2020-04-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20200424_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='tax_number',
            new_name='fiscal_number',
        ),
        migrations.AlterField(
            model_name='client',
            name='date_last_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Spouse'),
        ),
    ]
